### ISSUE TITLE
Make store.getId() fail-safe

### ISSUE THREAD

**Issue by kabirbaidhya** [leapfrogtechnology/async-store#15]
https://github.com/leapfrogtechnology/async-store/blob/3a4f124e931a8b24b8a63c159650179f375d3f65/src/index.ts#L166

https://github.com/leapfrogtechnology/async-store/blob/3a4f124e931a8b24b8a63c159650179f375d3f65/src/impl/domain.ts#L194-L213

@cham11ng We either need to make `store.getId()` fail-safe like `find()` or we'll need to create a new fail-safe version eg: `findId()`. 

cc @mesaugat

**Comment by cham11ng** [comment]
If the `domain` is not found, it returns `undefined`. It's already safe.

**Comment by kabirbaidhya** [comment]
Yes, we need a couple of tests to make sure this is fail-safe.

**Comment by cham11ng** [comment]
Added some test cases for getId()

https://github.com/leapfrogtechnology/async-store/pull/18
